DROP TABLE Clientes;
CREATE TABLE Clientes (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    apellido VARCHAR2(50),
    fecha_registro DATE,
    email VARCHAR2(100),
    telefono VARCHAR2(15)
);

DROP TABLE Productos;
CREATE TABLE Productos (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR2(100),
    categoria VARCHAR2(50),
    precio NUMBER(10, 2),
    stock NUMBER
);

DROP TABLE Ventas;
CREATE TABLE Ventas (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    product_id NUMBER,
    cantidad NUMBER,
    fecha_venta DATE,
    total_venta NUMBER(10, 2)
);

DROP TABLE Personal_de_Ventas;
CREATE TABLE Personal_de_Ventas (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    apellido VARCHAR2(50),
    email VARCHAR2(100),
    telefono VARCHAR2(15)
);

-----------------------
INSERT INTO Clientes (nombre, apellido, fecha_registro, email, telefono) VALUES
('Juan', 'Pérez', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'juan.perez@example.com', '555-1234');
INSERT INTO Clientes (nombre, apellido, fecha_registro, email, telefono) VALUES
('María', 'González', TO_DATE('2023-02-20', 'YYYY-MM-DD'), 'maria.gonzalez@example.com', '555-5678');
INSERT INTO Clientes (nombre, apellido, fecha_registro, email, telefono) VALUES
('Luis', 'Fernández', TO_DATE('2023-03-10', 'YYYY-MM-DD'), 'luis.fernandez@example.com', '555-8765');
INSERT INTO Clientes (nombre, apellido, fecha_registro, email, telefono) VALUES
('Ana', 'Martínez', TO_DATE('2023-04-05', 'YYYY-MM-DD'), 'ana.martinez@example.com', '555-4321');
INSERT INTO Clientes (nombre, apellido, fecha_registro, email, telefono) VALUES
('Pedro', 'López', TO_DATE('2023-05-25', 'YYYY-MM-DD'), 'pedro.lopez@example.com', '555-3456');


INSERT INTO Productos (nombre_producto, categoria, precio, stock) VALUES
('Laptop Gaming', 'Computadoras', 1200.00, 10);
INSERT INTO Productos (nombre_producto, categoria, precio, stock) VALUES
('Smartphone', 'Celulares', 700.00, 25);
INSERT INTO Productos (nombre_producto, categoria, precio, stock) VALUES
('Auriculares Bluetooth', 'Accesorios', 150.00, 50);
INSERT INTO Productos (nombre_producto, categoria, precio, stock) VALUES
('Smartwatch', 'Relojes', 200.00, 30);
INSERT INTO Productos (nombre_producto, categoria, precio, stock) VALUES
('Tablet', 'Computadoras', 300.00, 20);

INSERT INTO Ventas (customer_id, product_id, cantidad, fecha_venta, total_venta) VALUES
(1, 1, 1, TO_DATE('2023-06-01', 'YYYY-MM-DD'), 1200.00);
INSERT INTO Ventas (customer_id, product_id, cantidad, fecha_venta, total_venta) VALUES
(2, 2, 2, TO_DATE('2023-06-05', 'YYYY-MM-DD'), 1400.00);
INSERT INTO Ventas (customer_id, product_id, cantidad, fecha_venta, total_venta) VALUES
(3, 3, 3, TO_DATE('2023-06-10', 'YYYY-MM-DD'), 450.00);
INSERT INTO Ventas (customer_id, product_id, cantidad, fecha_venta, total_venta) VALUES
(4, 4, 1, TO_DATE('2023-06-15', 'YYYY-MM-DD'), 200.00);
INSERT INTO Ventas (customer_id, product_id, cantidad, fecha_venta, total_venta) VALUES
(5, 5, 2, TO_DATE('2023-06-20', 'YYYY-MM-DD'), 600.00);

INSERT INTO Personal_de_Ventas (nombre, apellido, email, telefono) VALUES
('Carlos', 'Sánchez', 'carlos.sanchez@example.com', '555-1111');
INSERT INTO Personal_de_Ventas (nombre, apellido, email, telefono) VALUES
('Laura', 'Ramírez', 'laura.ramirez@example.com', '555-2222');
INSERT INTO Personal_de_Ventas (nombre, apellido, email, telefono) VALUES
('Javier', 'Torres', 'javier.torres@example.com', '555-3333');
INSERT INTO Personal_de_Ventas (nombre, apellido, email, telefono) VALUES
('Sofía', 'Hernández', 'sofia.hernandez@example.com', '555-4444');
INSERT INTO Personal_de_Ventas (nombre, apellido, email, telefono) VALUES
('Diego', 'Morales', 'diego.morales@example.com', '555-5555');


